name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

          
      
        - uses: mr-smithers-excellent/docker-build-push@v6
          name: Build & push Docker image
          with:
            image: sloair/sa_p2
            tags: alpha
            registry: docker.io
            dockerfile: sp/test/QueryMe/Dockerfile
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
