name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
        
        - uses: mr-smithers-excellent/docker-build-push@v6
          name: Build & push Docker image
          with:
            image: sloair/sa_p2
            tags: alpha
            registry: docker.io
            dockerfile: sp/test/QueryMe/Dockerfile
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
  
  webhook:
    
      runs-on: ubuntu-latest
      needs: build
      
      steps:
        - name: Send cURL request
          run: |
              curl -X POST -H "Content-Type: application/json" -d '{"text": "QueryMe Hook"}' ${{ secrets.WEBHOOK_URL }}
